version: '3.8'

services:
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - polls_pg_data:/var/lib/postgresql/data
    networks:
      - finances

volumes:
  polls_pg_data:

networks:
  finances:
